//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Runtime.CompilerServices;

namespace APPID.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string lastDir {
            get {
                return ((string)(this["lastDir"]));
            }
            set {
                this["lastDir"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool Goldy {
            get {
                return ((bool)(this["Goldy"]));
            }
            set {
                this["Goldy"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool Pinned {
            get {
                return ((bool)(this["Pinned"]));
            }
            set {
                this["Pinned"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool AutoCrack {
            get {
                return ((bool)(this["AutoCrack"]));
            }
            set {
                this["AutoCrack"] = value;
            }
        }

        public bool ZipDontAsk { get; internal set; }
        public string ZipFormat { get; internal set; }
        public string ZipLevel { get; internal set; }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool UseRinPassword {
            get {
                return ((bool)(this["UseRinPassword"]));
            }
            set {
                this["UseRinPassword"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool LANMultiplayer {
            get {
                return ((bool)(this["LANMultiplayer"]));
            }
            set {
                this["LANMultiplayer"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string SharedGamesData {
            get {
                return ((string)(this["SharedGamesData"]));
            }
            set {
                this["SharedGamesData"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5000000")]
        public double LastUploadRate {
            get {
                return ((double)(this["LastUploadRate"]));
            }
            set {
                this["LastUploadRate"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("50000000")]
        public double LastZipRateLevel0 {
            get {
                return ((double)(this["LastZipRateLevel0"]));
            }
            set {
                this["LastZipRateLevel0"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30000000")]
        public double LastZipRateCompressed {
            get {
                return ((double)(this["LastZipRateCompressed"]));
            }
            set {
                this["LastZipRateCompressed"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool SkipPyDriveConversion {
            get {
                return ((bool)(this["SkipPyDriveConversion"]));
            }
            set {
                this["SkipPyDriveConversion"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string UploadBandwidthLimit {
            get {
                return ((string)(this["UploadBandwidthLimit"]));
            }
            set {
                this["UploadBandwidthLimit"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int CompressionLevel {
            get {
                return ((int)(this["CompressionLevel"]));
            }
            set {
                this["CompressionLevel"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("ZIP")]
        public string CompressionFormat {
            get {
                return ((string)(this["CompressionFormat"]));
            }
            set {
                this["CompressionFormat"] = value;
            }
        }
    }
}
